### ISSUE TITLE
Android App - permissions: RECORD_AUDIO

### ISSUE THREAD

**Issue by gvarisco** [italia/cie-ideaapp#5]
According to its manifest, the app requires `android.permission.RECORD_AUDIO`. Such permission allows the application to access the audio record path. 
```
URI: android.permission.RECORD_AUDIO
Risk: MODERATE-HIGH
Protection level: DANGEROUS

Official Description
Allows an application to record audio
```
I'm not entirely familiar with the app's features, but unless we require it for legitimate uses such as note taking or voice search, I'd drop this requirement in the next releases.

@andemaria can you please clarify it?

**Comment by andemaria** [comment]
the card data used for access the chip (date of birth, card number, card expiry) can be given also by voice.
