### ISSUE TITLE
Scansione passaporto

### ISSUE THREAD

**Issue by alranel** [italia/cie-ideaapp#7]
In [questa recensione](https://play.google.com/store/apps/details?id=it.ipzs.nfccardreader&reviewId=Z3A6QU9xcFRPRy1tZ3Zqdm5vWi11MktHVWVkNWtnVkJTcXVfX0Zmem5hV1FqczZmaUktWlVnTWRFbnNyUVJiYkpXLTFMdXMyQzFGR0Zwa1BtQVFLb2pJMWow) viene segnalato che non si riesce a leggere il passaporto. Non ho avuto modo di verificare personalmente. Qualcuno può aiutarci a testare e risolvere?

**Comment by ghost** [comment]
Ciao @alexrj, la lettura del codice MRZ tramite fotocamera funziona sia su CIE che su PE. 
Essendo però una lettura ottica sia la scarsa luminosità o la qualità della fotocamera possono condizionare i tempi di lettura.
Nella fattispecie del PE la pellicola di sicurezza applicata sul codice MRZ è particolarmente riflettente e può accadere che se non si fa attenzione i riflessi della luce rendono irriconoscibili alcuni caratteri durante la scansione.
Provvediamo a rispondere al commento.

**Comment by alranel** [comment]
Grazie per il chiarimento! Allora chiudo questa issue.
